# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7b1f2de3d29f3f0341b99a9ea776ad630fa59904ea3b75eda16158b405ee4e98e2c52730fd43c419e262664ff50c463bf2db4e31b0aa1dadf65041bf166bd1e

test:
  secret_key_base: 0ec1af2638d8147117023a04e8cb81b751e5e820ab98671c4fcd76e4a312d2b9c27178ef39e6a0a202bfe7098ea2d7493666402ee87061fc8d5ce2fb1ac428b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
